-- 20260811000001 — Fotoja e faturës: a photo of the paper receipt, attached to
-- a club expense row.
--
-- WHY A PATH ON THE ROW, AND NOT A public.media ROW
-- -------------------------------------------------
-- public.media is the CMS library: things an editor picks from a grid and
-- reuses across news, races and sponsors. A receipt is the opposite of that —
-- it belongs to exactly one expense, it is never reused, and it must never
-- surface in the picker an editor browses while writing an article. So it goes
-- where /join already puts an applicant's photo: a random object under a path
-- prefix in the `media` bucket, with the PATH stored on the owning row
-- (applications.photo_storage_path, migration 20260518000005). One column, and
-- the object's lifetime is the row's lifetime.
--
-- ONE receipt, not many. The owner photographs a till slip in a bike shop; the
-- 2026 sheet already carries "Nr. Fatures" as a single value per line. A
-- one-to-many table would be a join, an ordering column and a delete cascade
-- bought for a case that does not exist yet. text, nullable, and null means
-- "no photo" — not "photo missing", exactly as amount_eur's null means "price
-- not agreed" and never zero.
alter table public.club_expenses
  add column if not exists receipt_path text;

comment on column public.club_expenses.receipt_path is
  'Path of the receipt photo inside the `media` storage bucket, e.g. '
  '"receipts/<32 hex>.jpg". NULL = no photo attached. The object is removed by '
  'the server action when the receipt is replaced or the expense is deleted.';

-- The path is generated by the server action, never typed, so it can be pinned
-- exactly. This is what makes the storage policies below safe to scope: a row
-- can only ever point INTO receipts/, so an expense can never be used to hand
-- out a link to somebody's application photo or to a private object.
alter table public.club_expenses
  drop constraint if exists club_expenses_receipt_path_ck;
alter table public.club_expenses
  add constraint club_expenses_receipt_path_ck
  check (
    receipt_path is null
    or receipt_path ~ '^receipts/[0-9a-f]{32}\.(jpg|png|webp)$'
  );

-- ============================================================
-- Storage: who may put a receipt into the media bucket.
--
-- Migration 0009 gives the media bucket "media editor write" / "media editor
-- delete", both limited to admin + EDITOR. Expenses are admin + STAFF
-- (club_expenses_write_staff, migration 20260810000002), so as things stand a
-- staff member can insert the expense row and then fail on the upload — the
-- exact half-saved state app/join/actions.ts is careful to avoid.
--
-- These two policies are ADDITIVE and NARROW: they add admin+staff, and only
-- under the receipts/ prefix. Nothing existing is widened — an editor keeps
-- what it had everywhere else in the bucket, and a staff member gains nothing
-- outside receipts/. (Postgres OR-combines permissive policies, so a plain
-- `create policy` here cannot subtract from another one either.)
--
-- READS. The media bucket is public, and this migration deliberately does not
-- change that: narrowing "media public read" would take the club's news and
-- race photos offline. A receipt is therefore readable by anyone who has the
-- URL, and its only protection is that the filename is 128 bits of randomness
-- that appears nowhere but in an admin-only page. That is the same posture the
-- club already accepts for applicants' photos. If receipts ever need to be
-- genuinely private they belong in the `documents` bucket behind signed URLs —
-- a different change, with a different reader.
-- ============================================================
drop policy if exists "media expense receipt insert" on storage.objects;
create policy "media expense receipt insert" on storage.objects
  for insert
  to authenticated
  with check (
    bucket_id = 'media'
    and name like 'receipts/%'
    and public.has_role(array['admin','staff']::public.user_role[])
  );

-- Replacing a receipt must not leave the old JPEG behind, and deleting an
-- expense must take its photo with it. Both are the same DELETE, so staff need
-- it for the rows they are allowed to write anyway.
drop policy if exists "media expense receipt delete" on storage.objects;
create policy "media expense receipt delete" on storage.objects
  for delete
  to authenticated
  using (
    bucket_id = 'media'
    and name like 'receipts/%'
    and public.has_role(array['admin','staff']::public.user_role[])
  );

-- No UPDATE policy on purpose: an object under receipts/ is immutable. A
-- replacement is a new random path plus a delete of the old one, so a stale
-- CDN copy can never be served for a receipt that has been swapped.

-- NO INDEX on `receipt_path is null`, deliberately. The "Pa foto të faturës"
-- chip on /admin/finance/expenses does not filter in SQL: that page reads one
-- year of rows and applies every filter but the year in JS, precisely so the
-- totals printed above the list cannot disagree with the list. A partial index
-- would therefore never be planned — it would only cost a write on every
-- expense inserted or edited. If receipts ever get their own SQL-side report,
-- the index belongs in that migration, next to the query that uses it.
